### ISSUE TITLE
[Feature] Update default messages for empty fields in export view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3449]
Design task #3345

**Description and related issues -**
Some of the fields in the eAPD will not be required to be answered before submit. We have language that we use, noted in the content guide in the wiki, to note when a field isn't filled out so that it's clear to the reviewer that it wasn't a mistake or something broken in the system, but we only did this for top fields before release. Update the other fields to have default values.

### Activity
* Provide a short overview of summary
```
No response was provided.
```
* Statement of Alternative Considerations and Supporting Justification
```
No response was provided. 
```
* Outcomes and Metrics
  * Use `No outcome(s) and corresponding metrics were provided.` when the section is missing at least one outcome and metrics
  * Use `No metrics were specified for this outcome.` when an outcome is included but no metrics.
* Milestones
  * Use `No milestones were provided.` for an empty milestone section
* State Staff
```
State staff not specified.
```
* Other state expense
```
Other state expenses not specified.
```
* Private Contractor
```
Private contractor(s) not specified.
```
* Description of Cost Allocation Methodology
```
No cost allocation methodology was provided.
```
* Other funding description
```
No response was provided.
```
* Budget and Federal Financial Participation (FFP)
```
No response was provided for the Budget and FFP.
```

![Screen Shot 2021-08-30 at 2.53.10 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/00c8db76-0fec-40c6-a8a5-6053e2d37054)

### Activity Schedule Summary

* Activity milestones
  * Use `Activity X: Untitled | No milestones were provided` if the activity is unnamed and there are no milestones.
  * Use `Activity X: Untitled Milestones` if there are milestones but the activity is not unnamed.
  * Use `No milestones to display.` in the table cell if there are no milestones.
  * Use `Dates not specified` when the Activity Date Range is not available.
  * Use `Milestone name not specified.` if a milestone is unnamed. 

![Screen Shot 2021-08-30 at 2.52.12 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/836fcac2-0455-4d6c-969c-c2b9478275ca)

### Assurances and Compliance

* Each field would have no response was provided. i.e.: 
```
Does this project comply with 42 CFR Part 495.348?
No response was provided.
```

![Screen Shot 2021-08-30 at 2.52.28 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/036c497d-b243-478d-9a06-c4a264fd94b9)

**Mockups or link to Figma**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3524%3A0

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4741%3A31123

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4743%3A31165

### This task is done when…

- [ ] all of the above default values have been updated
- [ ] all tests, including e2e tests, have been updated to match the changes

**Comment by tbolt** [comment]
@akuas @thetif @jeromeleecms For Budget and FFP section, we default to a 90-10 split, because of that we can't determine wether they "chose" that or didn't respond. So i'm not sure how to determine when they haven't provided a response. This is the section with budget tables so i'm wondering if the idea is to not show them if all the totals are 0 AND its set to 90-10 split?

**Comment by jeromeleecms** [comment]
@tbolt A while back we changed the default to no selection - by default, the calculation is a 0-100 Federal/State split which is then updated when the user makes the selection. This idea of "no selection" should be present in most the app which requires that the state make a decision vs. have the app make a default decision for them.

![image](https://user-images.githubusercontent.com/34279968/164746277-be61d3e3-9889-4b8f-a37b-ea57fd35b3dd.png)

Does that help?

**Comment by tbolt** [comment]
@jeromeleecms I thought that was the case, but from what I can tell that logic hasn't been implemented in the codebase. 

That sounds good though. Just to clarify though- If they don't select an option for Federal-State Split, is the intent to not show the tables at all in the export view?

**Comment by akuas** [comment]
@jeromeleecms That sounds good to have the select an option as a default. I created a new APD and 90-10 was the default so I imagine to code has to be amended to make users select an FFP instead of 90-10 being the default. And this would be the same for other dropdowns i imagine.
So, if part of the Budget and FFP page is filled out and one year doesnt have an FFP should we say " FFP not specified"?

**Comment by tbolt** [comment]
Doing some digging I did find that we had updated it to be 0-100. However, it was not updated in one place so doing "Create New APD" was still defaulting to 90-10. I have this corrected/fixed now.

**Comment by tbolt** [comment]
@jeromeleecms with the fed-state split issue resolved, @akuas and I thought it would be best to not have a message for this case and just have the budget tables show $0 as an indicator that nothing has been entered. Let me know if you have any concerns with that.

**Comment by jeromeleecms** [comment]
1) Good with no message with no selection for the fed-state split
2) If they don't make selection the math should still show as 0-100 and that would be reflected in the builder and the export view correct?

**Comment by tbolt** [comment]
@jeromeleecms for #2 that's correct. If no selection is made both the builder and export view show a 0-100 split. Here's an example of the export view-
![Screen Shot 2022-04-25 at 12.54.03 PM.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/c8d0285b-9797-4f42-8001-28f67df29ea1)

**Comment by jeromeleecms** [comment]
Looks good!
